{% set name = "hybgensea" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hybgensea-{{ version }}.tar.gz
  sha256: b733b09ccd77616107109ad08b684ca6b5a91a52c821112569c341a4a80f1043

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - nanobind
  host:
    - python
    - scikit-build-core
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - hybgensea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdealencar/HybGenSea
  summary: Wrapper for the Hybrid Genetic Search algorithm for Capacitated Vehicle Routing Problems (HGS-CVRP)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdealencar
    - simutisernestas
